version: '3'
services:
  runquery:
    image: runquery
    volumes:
      - instance:/usr/var/runquery-instance/
    env_file:
      - app.env

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - runquery
    ports:
      - 8282:80

volumes:
    instance:

