FROM alpine
EXPOSE 3031
RUN apk add --no-cache \
        uwsgi-python3 \
        python3 \
        git \
        py3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt

VOLUME /usr/src/app/
WORKDIR /usr/src/app
USER 1000

ENV FLASK_APP runquery
ENV FLASK_ENV development
ENV INSTANCE_DIR ./instance
ENV DEBUG_MODE TRUE

CMD [ "python3", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "8282"]

