version: '3'
services:
  uwsgi-query:
    image: uwsgi-query
    volumes:
      - query-instance:/usr/var/strava_query-instance/
    env_file:
      - app.env

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uwsgi-query
    ports:
      - 8282:80

volumes:
    query-instance:

