FROM alpine:3.7
EXPOSE 3031
RUN apk add --no-cache \
        uwsgi-python \
        python \
        git \
        py-pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

VOLUME /usr/src/app/
WORKDIR /usr/src/app
USER 1000

ENV FLASK_APP runquery
ENV FLASK_ENV development
ENV INSTANCE_DIR ./instance
ENV DEBUG_MODE TRUE

CMD [ "python", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "8282"] 

